femme/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    url(r'^femme-admin/', admin.site.urls),
    url(r'^',include('web.urls',namespace="web")),

    url(r'^media(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),

    
]

web/urls.py
   
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^about/$',views.about, name="about"),
    url(r'^registration/$',views.registration, name="registration"),
]
 

web/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Registration(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField()
    phone = models.CharField(max_length=128)
    education = models.CharField(max_length=128)
    dob = models.DateField(blank=True,null=True)
    message = models.TextField()
                      
    class Meta:
    	db_table = 'web_registration'
    	verbose_name = _('registration')
    	verbose_name_plural = _('registrations')

    def _unicode_(self):
        return self.name

class About(models.Model):
    title = models.CharField(max_length=128)
    content = models.TextField()
    image = models.ImageField(upload_to="web/about/")
    subheading = models.CharField(max_length=128) 
    date_added = models.DateField()

    class Meta:
        db_table = 'web-about'
        verbose_name = "about"
        verbose_name_plural = "about"

    def _unicode_(self):
        return self.title
   

web/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea
from django.utils.translation import ugettext_lazy as _
from web.models import Registration


class RegistrationForm(forms.ModelForm):

	class Meta:
		model = Registration
		fields = '__all__'
		widgets = {
			'name':TextInput(attrs={'class': 'required', 'placeholder': 'Name'}),
			'email':TextInput(attrs={'class': 'required', 'placeholder': 'Email'}),
			'phone':TextInput(attrs={'class': 'required', 'placeholder': 'Phone'}),
			'education':TextInput(attrs={'class': 'required', 'placeholder': 'Education'}),
			'dob':Textarea(attrs={'class': 'required', 'placeholder': 'Dob'}),
			'message':TextInput(attrs={'placeholder': 'Message'}),
		}
		error_messages = {
			'name':{
				'required':_("name fielsd is required."),
				},
			'phone':{
				'required':_("phone field is required."),
				},
			'email':{
				'required':_("email fielsd is required."),
				},
			'education':{
				'required':_("education fielsd is required."),
				},
			'message':{
				'required':_("message fielsd is required."),
				}

		} 
		labels = {
			"email" : "enter your E-mail",
			"message" : "what is on your mind"
		}

web/views.py
       
from __future__ import unicode_literals
from django.shortcuts import render
from django.http.response import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from web.models import About, Registration
from web.forms import RegistrationForm
from web.functions import generate_form_errors
import json

def index(request):
    about_datas =  About.objects.all()
    form = RegistrationForm()
    context = {
        "title": "FEMME",
        "caption": "femme caption",
        "about_datas":about_datas,
        "form" : form,
        "is_home" : True
   
    }
    return render(request,'web/index.html',context)


def about(request):
    about_datas =  About.objects.all()
    context = {
    	"title": "about",
    	"about_datas":about_datas,
        "is_about" : True
   
    }
    return render(request,'web/about.html',context)


def registration(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            response_data = {
                "status" : "true",
                "title" : "Successfully created",
                "message" : "Registration Successfully Updated.",
               
            }
        else:
            message = generate_form_errors(form,formset=False)     

            response_data = {
                "status" : "false",
                "stable" : "true",
                "title" : "Form validation error",
                "message" : message
            }
            
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        return HttpResponse("invalid request")

templates/web/about.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
	<section id="about">
		<section class="wrapper">
			<ul>
				{% for about in about_datas %}
				<li>
					<div class="top">
						<div class="img">
							<img src="{{about.image.url}}" alt="" title="">
						</div>
					</div>
					<div class="bottom">
						<h3>{{about.title}}</h3>
						<h5>{{about.subheading}}</h5>
						<p>{{about.content}}</p>
						<p>{{about.date_added}}</p>
					</div>
				</li>
             {% endfor %}
			</ul>
			<br class="clear">
		</section>
	</section>
{% endblock %}
            
		

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}
		<meta charset="utf-8" />
		<title>{{title}}| {{caption}}</title>
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />
		<link rel="stylesheet" href="{% static 'css/style.css' %}"type="text/css" />
		<link rel="stylesheet" href="{% static 'css/sweetalert.css' %}"type="text/css" />
		<meta name="viewport" content="width=device-width; initial-scale=1.0" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
		<script src="{% static '/js/sweetalert.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	</head>
	<body>
		<section id="top">
			<section class="wrapper">
				<header>
					<h1><a href="index.html" title="Femme"><img src="{% static 'images/header-logo.png' %}" alt="image" title="Femme"/></a></h1>
					<div id="myNav" class="sidenav" onclick="closeNav()">
						<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
						<div class="overlay-content">
					    	<ul>
								<li><a onclick="closeNav()" href="{% url 'web:index' %}" title="Home">Home</a></li>
								<li><a onclick="closeNav()" href="{% url 'web:about' %}" title="About">About</a></li>
								<li><a onclick="closeNav()" href="{% url 'web:index' %}#features" title="Features">Features</a></li>
								<li class="last"><a onclick="closeNav()" href="{% url 'web:index' %}#contact" title="">Contact</a></li>
							</ul>
						</div>
					</div>
					<span class="openmenu" onclick="openNav()">&nbsp;</span>
					<br class="clear" />
				</header>
				{% if is_home %}
					{% include 'web/includes/index-spotlight.html' %}
				{% elif is_about %}
					{% include 'web/includes/about-spotlight.html' %}
				{% endif %}
			</section><!--(#top > .wrapper)-->
		</section><!--(#top)-->

		{% block content %}

		{% endblock%}

		<section id="contact">
			<section class="wrapper">
				<div class="head">
					<h3>Get in Touch</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam asperiores tenetur aliquid sit repellat, dolores eius quasi possimus ipsum explicabo cumque. Explicabo exercitationem dignissimos asperiores unde et est, expedita numquam?</p>
				</div>
				<ul>
					<li>
						<span><b class="icon icon1">&nbsp;</b></span>
						<p>2nd Floor,<br>Ashtamudi Tower,<br>SEZ IT Building Technopark <br>Kollam - 691501</p>
					</li>
					<li>
						<span><b class="icon icon2">&nbsp;</b></span>
						<p><a title="Email" href="mailto:hello@femme.com"> hello@femme.com</a></p>
					</li>
					<li>
						<span><b class="icon icon3">&nbsp;</b></span>
						<p><a title="Phone" href="tel:"> +91 9845213212</a></p>
						<p><a title="Phone" href="tel:">+91 9684578632</a></p>
					</li>
				</ul>
				<br class="clear">
				<span class="line one">&nbsp;</span>
				<section class="bottom">
					<a href="#" title="Twitter" target="_blank" class="icon Twitter"><img src="{% static 'images/tw.png' %}" alt="Image" title="Twitter" /></a>
					<a href="#" title="Facebook" target="_blank" class="fb"><img src="{% static 'images/fb.png' %}" alt="Image" title="Facebook" /></a>
					<a href="#" title="Google Plus" target="_blank" class="icon gplus"><img src="{% static 'images/gp.png' %}" alt="Image" title="Google Plus" /></a>
				</section>
			</section>
		</section>


		
		<footer>
			<section class="wrapper">
				<p>Powered By Femme. <span>&copy;</span> {% now 'Y' %} Femme. All rights reserved.</p>
			</section><!--(#footer > .bottom)-->
		</footer>
		<script>
			function openNav() {
			    document.getElementById("myNav").style.height = "100%";
			}

			function closeNav() {
			    document.getElementById("myNav").style.height = "0%";
			}
		</script>
	</body>
</html>

templates/web/includes/about-spotlight.html
<section id="spotlight">
	<h2>about</h2>
</section><!--(#top > .wrapper > #spotlight)-->

templates/web/includes/index-spotlight.html
<section id="spotlight">
	<h2>The Secret of getting <br>Ahead is getting started</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab nobis culpa magni, quod vel a maxime deleniti error officia odit, dicta laudantium cumque nostrum maiores beatae laboriosam eius, aut alias?</p>
	<a title="Explore" href="#" class="button">Explore</a>
</section><!--(#top > .wrapper > #spotlight)-->